name: BattleRoyale
main: com.tyoku.BattleRoyale
authors: [tyoku, Mayomi]
version: 0.1.0
commands:
   setroom:
      description: 初回スポ`ン位置をO定します。オプションでx,y,z座摔蛘数で指定も可能。
      usage: /setroom [x y x]
   brgame:
      description: バトロワの_始とK了を操作。またはF在のステ`タスを参照します。
      usage: /brgame [start|stop|status]
   setbrarea:
      description: ゲ`ムエリアを分校を中心に何マスで行うかO定する。
      usage: /setbrarea [n]
   brbuild:
      description: BR特有の建造物を作成します。setでポジション１、２の立方体と建造物の中心をO定します。saveで名前をつけて建造物を保存します。createで指定の建造物を建Bします。listで保存している建造物名の一Eを表示します。
      usage: /brbuild [[list] [create <name>] [save <name>] [set [1|2|home]]]
   brblist:
      description: ゲ`ムエリア内に建Bされた建物の座摔虿握栅工搿
      usage: /brblist
   brvotemap:
      description: ワ`ルドを再作成するか否かの意思を示します。m成割合や人数により、ワ`ルド再Bのためにサ`バを落とします。
      usage: /brvotemap <yes|no>
